### PR TITLE
Update the logo

### PR DESCRIPTION
**Pull request by eugeneo**

### CODE REVIEW

**Comment by PopeyeSailorMike** [comment]
Apply design and static page of one Astro template to another template that has blog support

https://www.loom.com/share/a93d79a6560d4e559cdda0c5ac361804

**Comment by PopeyeSailorMike** [comment]
Hi. I'm available right now. Are you still looking to do this?

**Comment by eugeneo** [comment]
@PopeyeSailorMike thank you for your interest in this project. I am currently clarifying requirements and soliciting proposals on the Upwork. Please do not contact me outside of Upwork platform.

**Comment by eugeneo** [comment]
Merged in #11

**Pull request closed without merging**
